### PR TITLE
Update Azure Container App Egress Lockdown

### PR DESCRIPTION
**Pull request by simonkurtz-MSFT**
Fix syntax issue in README.md
Add high-fidelity, execution-ready shell script

### CODE REVIEW

**Comment by simonkurtz-MSFT** [comment]
@swgriffith, here's the PR I mentioned I might create.

**Comment by simonkurtz-MSFT** [comment]
TODO for me later today: Add a Log Analytics Workspace and send logs and metrics from AFW to the LAW. This will then demonstrate via logs that AFW is allowing/blocking requests made from the ACA.

**Comment by swgriffith** [comment]
> 

I would maybe keep that separate. I like to keep these azure guides really short and sweet, otherwise the basics get lost in the noise.

**Comment by swgriffith** [comment]
@simonkurtz-MSFT  - Thanks for the PR!

**Comment by simonkurtz-MSFT** [comment]
> > 
> 
> I would maybe keep that separate. I like to keep these azure guides really short and sweet, otherwise the basics get lost in the noise.

I'm generally with you on that. Here, I am keeping the items fairly separate and contained in one section. I think it adds value to give more proof, but I also see what you're saying.

**Pull request merged**
